spring.application.name=chatClient-api



server.port=8080
spring.ai.openai.api-key=${groq_api}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

logging.level.org.springframework.ai=DEBUG


logging.level.org.springframework.ai.chat.client.advisor=DEBUG
